services:
  - type: web
    name: backend-solar
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend.jar
    envVars:
      - key: MYSQLHOST
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: MYSQLDATABASE
        sync: false
      - key: MYSQLPORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        sync: false